# Generated by Django 6.0.1 on 2026-02-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
    ]
