# Generated by Django 6.0.1 on 2026-03-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.TextField(max_length=20, unique=True)),
                ('last_name', models.TextField(max_length=100)),
                ('first_name', models.TextField(max_length=100)),
                ('street_number', models.TextField(max_length=10)),
                ('street_name', models.TextField(max_length=100)),
                ('apartment_number', models.TextField(blank=True, max_length=10)),
                ('zip_code', models.TextField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('date_of_registration', models.DateField()),
                ('party_affiliation', models.TextField(max_length=100)),
                ('precinct_number', models.TextField(max_length=20)),
                ('v20state', models.BooleanField(default=False)),
                ('v21town', models.BooleanField(default=False)),
                ('v21primary', models.BooleanField(default=False)),
                ('v22general', models.BooleanField(default=False)),
                ('v23town', models.BooleanField(default=False)),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
